http://localhost:3000/api/analytics/revenue-by-plan?tenant=acme

###

http://localhost:3000/api/analytics/revenue-by-plan?tenant=initech

###

http://localhost:3000/api/analytics/revenue-by-plan?tenant=globex


###

http://localhost:3000/api/analytics/revenue-by-plan?tenant=hooli


###

http://localhost:3000/api/analytics/revenue-by-plan?tenant=umbrella